#!/bin/zsh

#
# Text formatting
#
section() {
  echo ""
  echo "┌────────────────────────────────────────────────────────────────────────────────────────────────────"
  echo "│ $@"
  echo "└────────────────────────────────────────────────────────────────────────────────────────────────────"
  echo ""
}

step() {
  echo -e "[↓] $@"
}

success() {
  echo -e "[✓] $@\n"
}

skipped() {
  echo -e "[-] $@\n"
}


#
# Homebrew
#
install_brew() {
  local brew=$1

  if [[ ! $(brew list | grep $brew) ]]; then
    step "Installing $brew"
    brew install $brew >/dev/null
    success "$brew installed!"
  else
    skipped "$brew already installed. Skipped."
  fi
}

install_brew_cask() {
  local cask=$1

  if [[ ! $(brew cask list | grep $cask) ]]; then
    step "Installing $cask"
    brew cask install $cask --appdir=/Applications >/dev/null
    success "$cask installed!"
  else
    skipped "$cask already installed. Skipped."
  fi
}

install_app_store_app() {
  local app=$1
  local app_id=$2

  if [[ ! $(mas list | grep $app_id) ]]; then
    step "Installing $app"
    mas install $app_id >/dev/null
    success "$app installed!"
  else
    skipped "$app already installed. Skipped."
  fi
}

section "Install brew"
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

section "Update brew"
#brew update

section "Install all brews"
BREWS=(
  ansible
  awscli
  gh
  gnu-tar
  heroku
  jq
  mackup
  mas
  nmap
  rbenv
  redis
  ruby-build
  the_silver_searcher
  vim
  watch
)

for brew in ${BREWS[@]}; do
  install_brew $brew
done


section "Install all casks"
CASKS=(
  1password
  alfred
  dropbox
  firefox
  iterm2
  mailplane
  numi
  postgres
  spotify
)

for cask in ${CASKS[@]}; do
  install_brew_cask $cask
done


section "Add rbenv to .zshrc"
rbenv_init='if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi'
if [[ ! $(grep "$rbenv_init" ~/.zshrc) ]]; then
  step "Appending and reloading ~/.zshrc"
  echo "$rbenv_init" >> ~/.zshrc
  source ~/.zshrc
else
  skipped "rbenv init already found, skipped."
fi

section "Install ruby"
if [[ ! $(rbenv versions | grep "2.5.1") ]]; then
  step "Install ruby 2.5.1"
  rbenv install 2.5.1
  rbenv global 2.5.1
  ruby -v
else
  skipped "Ruby 2.5.1 already installed"
fi


section "Install oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


section "Install App Store apps"
typeset -A APPS=(
  Divvy 413857545
  Fantastical 975937182
  Keynote 409183694
  MicrosoftToDo 1274495053
  Pages 409201541
  Slack 803453959
  WhatsApp 1147396723
)

for app app_id in ${(kv)APPS}; do
  echo $app $app_id
  install_app_store_app $app $app_id
done
