#!/bin/zsh

#
# Text formatting
#
section() {
  echo ""
  echo "┌────────────────────────────────────────────────────────────────────────────────────────────────────"
  echo "│ $@"
  echo "└────────────────────────────────────────────────────────────────────────────────────────────────────"
  echo ""
}

step() {
  echo -e "[↓] $@"
}

success() {
  echo -e "[✓] $@\n"
}

skipped() {
  echo -e "[-] $@\n"
}


section "Install brew"
if test ! $(which brew); then
  step "Installing brew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  success "brew installed!"
else
  skipped "brew already installed, skipping"
fi

section "Update brew"
brew update

section "Install all apps from Brewfile"
brew tap "homebrew/bundle"
brew bundle --no-upgrade


section "Add rbenv to .zshrc"
rbenv_init='if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi'
if [[ ! $(grep "$rbenv_init" ~/.zshrc) ]]; then
  step "Appending and reloading ~/.zshrc"
  echo "$rbenv_init" >> ~/.zshrc
  source ~/.zshrc
else
  skipped "rbenv init already found, skipped."
fi

section "Install ruby"
if [[ ! $(rbenv versions | grep "2.5.1") ]]; then
  step "Install ruby 2.5.1"
  rbenv install 2.5.1
  rbenv global 2.5.1
  ruby -v
else
  skipped "Ruby 2.5.1 already installed"
fi


section "Install oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


section "Set up vim plugins"

if [[ ! -e ~/.vim/bundle/Vundle.vim ]]; then
  step "Installing Vundle"
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  success "Vundle installed"
else
  skipped "Vundle already found; skipping"
fi

step "Setting up vim plugins"
vim +PluginInstall +qall
